Repository LJIEUN/evenly-front, pull requests merged in 2025-03, with the labels that each got.

#2 로그인 페이지 생성
  src/app/components/layout/Header/Header.tsx
  src/app/components/layout/Layout.tsx
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
Labels: 🎨 UI

#3 회원가입 페이지 UI 기본 틀 생성
  src/app/auth/signup/SignupForm.tsx
  src/app/auth/signup/page.tsx
Labels: 🎨 UI

#4 공통 input UI 제작 및 로그인 폼 적용
  package-lock.json
  package.json
  postcss.config.mjs
  src/app/layout.tsx
  src/app/login/page.tsx
  src/components/auth/LoginForm/LoginForm.tsx
  src/components/common/Input/BaseInput.tsx
  src/components/common/Input/PasswordInput.tsx
  src/components/common/Input/TextInput.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Layout.tsx
  src/styles/global.css
  src/types/input.d.ts
Labels: 🎨 UI

#7 회원 가입 route.ts 추가, Tailwind CSS 커스텀 색상 설정 추가, API 연결
  src/app/api/auth/signup/route.ts
  src/app/auth/signup/SignupForm.tsx
  src/styles/global.css
  tailwind.config.ts
Labels: 🌟 feat

#8 마이페이지 UI 기본 틀 구현, API 연결
  src/app/api/auth/signup/route.ts
  src/app/api/mypage/route.ts
  src/app/auth/signup/SignupForm.tsx
  src/app/mypage/page.tsx
  src/styles/global.css
  tailwind.config.ts
Labels: 🐛 bug, 🎨 UI

#9 Base Button 추가 및 로그인 로직 추가
  src/app/api/auth/login/route.ts
  src/app/api/client.ts
  src/app/login/page.tsx
  src/components/auth/LoginForm/LoginForm.tsx
  src/components/auth/LoginForm/useLoginForm.ts
  src/components/common/Button/BaseButton.tsx
  src/components/common/Button/styles.ts
  src/types/auth.ts
  src/types/button.d.ts
  src/utils/validate.ts
Labels: 🌟 feat, 🎨 UI

#10 홈화면 헤더, 사이드바 추가
  src/components/layout/Header/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/SideBar/Sidebar.tsx
  src/styles/global.css
Labels: 🎨 UI

#11 마이페이지 (기능 추가, api 연동), 회원 정보 수정 페이지 (제작, 디자인, 기능, API 연결 & 연동), 기타 수정
  .env.example
  .gitignore
  src/app/api/mypage/route.ts
  src/app/mypage/EditForm.tsx
  src/app/mypage/page.tsx
  src/app/signup/SignupForm.tsx
  src/app/signup/page.tsx
Labels: 🌟 feat, 🎨 UI

#12 EditForm 리펙토링과 회원 탈퇴 구현 (Soft Delete)
  src/app/api/mypage/route.ts
  src/app/mypage/EditForm.tsx
  src/app/mypage/useEditPasswordForm.ts
Labels: 🌟 feat, ♻️ refactor

#13 홈화면 상품 리스트 추가
  next.config.ts
  src/app/api/product/route.ts
  src/app/page.tsx
  src/components/layout/Header/Header.tsx
  src/components/product/ProductCard.tsx
  src/components/product/ProductList/ProductList.tsx
  src/components/product/ProductList/useProductList.ts
  src/types/auth.d.ts
  src/types/auth.ts
  src/types/product.d.ts
Labels: 🌟 feat

#14 로그인 유지되도록 context 추가
  .env.example
  src/app/api/auth/login/route.ts
  src/app/api/client.ts
  src/app/api/product/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/auth/LoginForm/useLoginForm.ts
  src/components/layout/Header/Header.tsx
  src/hooks/useAuth.ts
  src/providers/AuthProvider.tsx
  src/providers/index.tsx
  src/types/auth.d.ts
  src/utils/decodeJwt.ts
Labels: 🌟 feat

#15 홈화면 페이지네이션 추가
  src/app/api/product/route.ts
  src/components/common/Pagination/Pagination.tsx
  src/components/layout/SideBar/Sidebar.tsx
  src/components/product/ProductList/ProductList.tsx
  src/components/product/ProductList/useProductList.ts
Labels: 🌟 feat

#16 배송 정보 UI 작성, 리펙토링과 오타 수정
  .env.example
  src/app/api/auth/signup/route.ts
  src/app/api/mypage/route.ts
  src/app/checkout/DeliveryForm.tsx
  src/app/checkout/page.tsx
  src/app/orders/page.tsx
  src/app/signup/SignupForm.tsx
  src/app/signup/useSignupForm.ts
  src/utils/validate.ts
Labels: 🐛 bug, 🎨 UI

#17 아이템 상세화면 구현
  package-lock.json
  package.json
  src/app/api/client.ts
  src/app/api/product/route.ts
  src/app/product/[id]/page.tsx
  src/components/common/Button/BaseButton.tsx
  src/components/common/Button/styles.ts
  src/components/common/Input/BaseInput.tsx
  src/components/common/Input/NumberInput.tsx
  src/components/product/ProductDetail/ProductDetail.tsx
  src/components/product/ProductDetail/useProductDetail.ts
  src/styles/global.css
  src/types/button.d.ts
  src/types/product.d.ts
  src/utils/format.ts
Labels: 🌟 feat, 🎨 UI

#18 배포 위해서 오류 임시 주석처리
  src/app/product/[id]/page.tsx
Labels: 🐛 bug

#21 메타데이터 설정
  public/favicon.svg
  public/favicon256x256.png
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/layout.tsx
Labels: 🌟 feat

#22 로그인 정보 마이페이지와 연동, CSS 와 버그 수정
  src/app/api/mypage/route.ts
  src/app/mypage/EditForm.tsx
  src/app/mypage/page.tsx
  src/app/mypage/useEditPasswordForm.ts
Labels: 🐛 bug, 🌟 feat

#23 장바구니 주문 API 연결
  public/favicon.svg
  src/app/api/orders/create/route.ts
  src/app/api/orders/route.ts
  src/app/cart/page.tsx
  src/components/cart/CartItemCard.tsx
  src/service/order.ts
  src/types/error.d.ts
  src/types/order.d.ts
Labels: 🌟 feat

#24 세로 스크롤 추가
  src/components/layout/Layout.tsx
Labels: 🌟 feat
